title: Fr. Conor Donnelly Meditations
description: A collection of meditations by Fr. Conor Donnelly
baseurl: "/meditations"  # The subpath of your site (important for GitHub Pages)
url: "https://frconor-ebook.github.io" # Your site's URL
permalink: /homilies/:title/
markdown: kramdown

# Build settings
source: .
destination: ./docs
plugins:
  - jekyll-feed

# Include an exclude
include:
  - "_data/"
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "vendor"
  - "create_project.sh"
  - "transcript_proofread_markdown_small/"
  - "transcript_proofread_markdown/"
  - "_posts/2025-02-03-welcome-to-jekyll.markdown"
  - "about.markdown"
  - "README.md"
  - "process_markdown.py"
  - ".gitignore"
  - "docs/README.md"

# Don't generate a sitemap for _data
defaults:
  - scope:
      path: ""
    values:
      sitemap: false